### PR TITLE
cleanup + feedback

### PR DESCRIPTION
**Pull request by ondrejch**
Let me know what you think.

### CODE REVIEW

**Comment by dmoser63** [comment]
To generalize the delayed constants, would it be better to have another input file with just the constants and add another command line argument, or include them with the reactivity in one input file?

**Comment by ondrejch** [comment]
On 12/16/2015 09:50 PM, Dallas Moser wrote:

> To generalize the delayed constants, would it be better to have 
> another input file with just the constants and add another command 
> line argument, or include them with the reactivity in one input file?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dmoser63/Neutron-Density/pull/4#issuecomment-165319924.
> 
> Yes I thought about this - the simplest would be to have say instead of 
> the LOGICAL we have now a number 1 through N for corresponding pre-sets, 
> and alternatively 0 followed by a file name for custom settings.

O.

**Comment by dmoser63** [comment]
Would the pre-sets only include the delayed constants?

**Comment by ondrejch** [comment]
Everything which is in Tab1 of the paper.

**Pull request merged**
